// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package io.zhangyj.proto3;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.zhangyj.proto3.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
