// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package io.zhangyj.proto3;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.zhangyj.proto3.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realName = 1;</code>
   * @return The realName.
   */
  java.lang.String getRealName();
  /**
   * <code>string realName = 1;</code>
   * @return The bytes for realName.
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
