// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package io.zhangyj.proto3;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.zhangyj.proto3.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
