// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package io.zhangyj.proto3;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_zhangyj_proto3_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_zhangyj_proto3_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_zhangyj_proto3_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_zhangyj_proto3_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_zhangyj_proto3_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_zhangyj_proto3_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_zhangyj_proto3_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_zhangyj_proto3_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_zhangyj_proto3_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_zhangyj_proto3_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_zhangyj_proto3_BiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_zhangyj_proto3_BiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_zhangyj_proto3_BiResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_zhangyj_proto3_BiResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\021io.zhangyj.proto3\"\035\n\tMy" +
      "Request\022\020\n\010userName\030\001 \001(\t\"\036\n\nMyResponse\022" +
      "\020\n\010realName\030\001 \001(\t\"\035\n\016StudentRequest\022\013\n\003a" +
      "ge\030\001 \001(\005\",\n\017StudentResponse\022\013\n\003age\030\001 \001(\005" +
      "\022\014\n\004name\030\002 \001(\t\"K\n\023StudentResponseList\0224\n" +
      "\010response\030\001 \003(\0132\".io.zhangyj.proto3.Stud" +
      "entResponse\"\031\n\tBiRequest\022\014\n\004uuid\030\001 \001(\t\"\032" +
      "\n\nBiResponse\022\014\n\004uuid\030\001 \001(\t2\356\002\n\tMyService" +
      "\022L\n\013GetRealName\022\034.io.zhangyj.proto3.MyRe" +
      "quest\032\035.io.zhangyj.proto3.MyResponse\"\000\022]" +
      "\n\020GetStudentsByAge\022!.io.zhangyj.proto3.S" +
      "tudentRequest\032\".io.zhangyj.proto3.Studen" +
      "tResponse\"\0000\001\022g\n\026GetStudentWrapperByAge\022" +
      "!.io.zhangyj.proto3.StudentRequest\032&.io." +
      "zhangyj.proto3.StudentResponseList\"\000(\001\022K" +
      "\n\006biTalk\022\034.io.zhangyj.proto3.BiRequest\032\035" +
      ".io.zhangyj.proto3.BiResponse\"\000(\0010\001B#\n\021i" +
      "o.zhangyj.proto3B\014StudentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_zhangyj_proto3_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_zhangyj_proto3_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_zhangyj_proto3_MyRequest_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_io_zhangyj_proto3_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_zhangyj_proto3_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_zhangyj_proto3_MyResponse_descriptor,
        new java.lang.String[] { "RealName", });
    internal_static_io_zhangyj_proto3_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_zhangyj_proto3_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_zhangyj_proto3_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_io_zhangyj_proto3_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_zhangyj_proto3_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_zhangyj_proto3_StudentResponse_descriptor,
        new java.lang.String[] { "Age", "Name", });
    internal_static_io_zhangyj_proto3_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_io_zhangyj_proto3_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_zhangyj_proto3_StudentResponseList_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_io_zhangyj_proto3_BiRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_io_zhangyj_proto3_BiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_zhangyj_proto3_BiRequest_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_io_zhangyj_proto3_BiResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_io_zhangyj_proto3_BiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_zhangyj_proto3_BiResponse_descriptor,
        new java.lang.String[] { "Uuid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
