// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package io.zhangyj.proto3;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.zhangyj.proto3.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.zhangyj.proto3.StudentResponse response = 1;</code>
   */
  java.util.List<io.zhangyj.proto3.StudentResponse> 
      getResponseList();
  /**
   * <code>repeated .io.zhangyj.proto3.StudentResponse response = 1;</code>
   */
  io.zhangyj.proto3.StudentResponse getResponse(int index);
  /**
   * <code>repeated .io.zhangyj.proto3.StudentResponse response = 1;</code>
   */
  int getResponseCount();
  /**
   * <code>repeated .io.zhangyj.proto3.StudentResponse response = 1;</code>
   */
  java.util.List<? extends io.zhangyj.proto3.StudentResponseOrBuilder> 
      getResponseOrBuilderList();
  /**
   * <code>repeated .io.zhangyj.proto3.StudentResponse response = 1;</code>
   */
  io.zhangyj.proto3.StudentResponseOrBuilder getResponseOrBuilder(
      int index);
}
